# Generated by Django 4.2.11 on 2024-03-13 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pay_status',
        ),
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('FLD', 'Fresh Learner Driving'), ('ALD', 'Advanced Learner Driving'), ('DD', 'Defensive Driving')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
